index.md
Maybe this could be added as a useful resource 😁
=> Add uselessshit nostr resources

index.md
Adding [nostrview.com](https://nostrview.com)
=> Add nostrview

index.md
new german translation at nostr-info.de
=> Add German translation

index.md
linking translation into italian at https://gist.github.com/theRescuer/717295270a35b4641081b6ef2cdf3025
=> Include a link to the translation into Italian

index.md
Damus is now available in normal app store
=> change damus link

_includes/navigation.html, index.md
Not sure if it's better or worse
=> feat: update structure, add action buttons

index.md
Remove Nosky because the project is abandoned and add Nozzle.
=> docs: Remove Nosky and add Nozzle

index.md
Added Nostr talk podcast by DK
=> Add Nostr Talk Podcast

_data/nip05providers.yml
I have no idea if you are still looking to add providers to your list. 
But if so, here is my small contribution.
=> Add the provider nostr-relay.org in the list of providers

index.md
-added note than clients may not verify signatures for incoming events 
-added privacy section
-add reference to most popular zapping wallet WOS
-added other miscellaneous add-ons & updates
=> Update Privacy Section

index.md
Repository got transferred to me a while ago
=> Fix link to Nozzle repository

index.md
https://nostr.band/ is really good
=> Add nostr.band to #search

index.md
Add nostrcheck.me to image hosts
=> Add nostrcheck.me to image hosts

index.md
Added more web clients, plebstr for android, profile tools and apps for content creators as well as self-custodial wallets.
=> Added more clients, wallets and tools

index.md
nostrgram.co seems to have gone offline (did not remove though)
=> add Nostur and Nootti

_includes/navigation.html, index.md
Small update, some new links, mostly re-wording.
=> feat: add FAQ section

index.md
=> feat(faq): update

index.md
I removed bounstr and the reference to bounties, and replaced with a donation prompt and links. I don't know of a currently functional bounty replacement.
=> replaced bounstr

index.md
=> Fix NostrSync link 

index.md
replacements and additions in Clients and Tools
=> some updates and additions

index.md
Added what I could find.
rss.nostr.band seems to be stopped or on hold
=> Update RSS section

index.md
-The Receiving Zaps section had a lot of needed changes. I hope I didn't overstep there. Please check my work :)
-Loosely updates Dm info
-also, removed nostrgram
=> Updated Receiving Zaps and Privacy & DM sections

index.md
start.njump.me changed to nstart.me
=> Update FAQ 'creating profile' answer

_data/nip05providers.yml
1 paid and 2 free providers are gone.
=> Removed defunct providers

index.md
Reviewing for the month looked good, so I went through the listed issues to add media resources. I included a few other good ones that were not noted here.
I did not add episode transcripts. Still figuring that out.
Resolves #54 #55 #56 #57
=> Add podcasts, episodes, and videos

index.md
Removes Feeder, as Feeder removed Nostr.
=> Updates RSS section index.md
